sudo: required

language: python

services:
  - docker

before_install:
  - sudo make travis
  - sudo sh -c "mkdir -p /etc/chains/devices; wget https://raw.githubusercontent.com/ChainsAutomation/chains/master/misc/examples/etc-master/chains.conf -O /etc/chains/chains.conf"
  - bin/dockerfile-assemble.py master
  - docker version
  - docker build --no-cache -t chains/chains-master .
  - docker run -d chains/chains-master
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push chains/chains-master

script:
  - docker ps -a
  - sleep 60
  - DOCKERID=`docker ps -q`; docker exec $DOCKERID /usr/bin/supervisorctl status

notifications:
  irc:
    channels:
      - "irc.freenode.net#chains"
    on_success: always
    on_failure: always
