sudo: required

language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"

services:
  - docker

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == "3.5" ]]; then export DEPLOY=true; else export DEPLOY=false; fi
  - sudo make travis
  - sudo sh -c "mkdir -p /etc/chains/devices; wget https://raw.githubusercontent.com/ChainsAutomation/chains/master/misc/examples/etc-master/chains.conf -O /etc/chains/chains.conf"
  - bin/dockerfile-assemble.py master
  - docker version
  - $DEPLOY && docker build --no-cache -t chains/chains-master .
  - $DEPLOY && docker run -d chains/chains-master

script:
  - $DEPLOY && echo "Builded container and ready to deploy" || "Only running tests"
  - $DEPLOY && docker ps -a
  - $DEPLOY && sleep 45
  - $DEPLOY && DOCKERID=`docker ps -q`; docker exec $DOCKERID /usr/bin/supervisorctl status > output
  - $DEPLOY && cat output
  - $DEPLOY && cat output | grep "FATAL" && exit 1 || echo "Every process started correctly"

after_success:
  - $DEPLOY && ./deploy.sh

notifications:
  irc:
    channels:
      - "irc.freenode.net#chains"
    on_success: always
    on_failure: always
