sudo: required

language: python
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"

services:
  - docker

before_install:
  - sudo make travis
  - sudo sh -c "mkdir -p /etc/chains/devices; wget https://raw.githubusercontent.com/ChainsAutomation/chains/master/misc/examples/etc-master/chains.conf -O /etc/chains/chains.conf"
  - bin/dockerfile-assemble.py master
  - docker version
  - docker build --no-cache -t chains/chains-master .
  - docker run -d chains/chains-master

script:
  - docker ps -a
  - sleep 45
  - DOCKERID=`docker ps -q`; docker exec $DOCKERID /usr/bin/supervisorctl status > output
  - cat output
  - cat output | grep "FATAL" && exit 1 || echo "Every process started correctly"

after_success:
  - ./deploy.sh

notifications:
  irc:
    channels:
      - "irc.freenode.net#chains"
    on_success: always
    on_failure: always
