sudo: required

language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"

services:
  - docker

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == "3.5" ]]; then export BUILD=true; else export BUILD=false; fi
  - if [[ $TRAVIS_BRANCH == "master" ]]; then export DEPLOY=true; else export DEPLOY=false; fi
  - $BUILD && echo "Will build, run and deploy" || echo "Will NOT build, run or deploy"
  - sudo make travis
  - sudo sh -c "mkdir -p /etc/chains/devices; wget https://raw.githubusercontent.com/ChainsAutomation/chains/master/misc/examples/etc-master/chains.conf -O /etc/chains/chains.conf"
  - bin/dockerfile-assemble.py master
  - docker version
  - $BUILD && docker build --no-cache -t chains/chains-master . || echo "NOT BUILDING"
  - $BUILD && docker run -d chains/chains-master || echo "NOT RUNNING"

script:
  - $BUILD && echo "Builded container and ready to deploy" || echo "Only running tests"
  - $BUILD && docker ps -a || echo ""
  - $BUILD && sleep 45 || echo ""
  - $BUILD && DOCKERID=`docker ps -q`; docker exec $DOCKERID /usr/bin/supervisorctl status > output || echo ""
  - $BUILD && cat output || echo ""
  - $BUILD && cat output | grep "FATAL" && exit 1 || echo "Every process started correctly"

after_success:
  - ./deploy.sh

notifications:
  irc:
    channels:
      - "irc.freenode.net#chains"
    on_success: always
    on_failure: always
