#!/bin/bash

# If this is the first time this container is started, 
# create some default configs if none exists.

ARCH=`uname -m`
if [ ! -f /chains-configured ]; then
    echo "First run, installing default configs"
    mkdir -p /etc/chains/services
    if [ ! -f /etc/chains/chains.yml ]; then
        cp /srv/chains/misc/Docker/chains-config/chains.yml-slave /etc/chains/chains.yml
    fi
    # Add some default services
    shopt -s nullglob
    files=(/etc/chains/services/*)
    shopt -u nullglob
    if [ ${#files[@]} -lt 1 ]; then
        if [[ (${ARCH} == 'x86_64') || (${ARCH} == 'i686') ]]; then
            echo "container is x86"
            cp /srv/chains/misc/Docker/chains-config/default-services-slave/* /etc/chains/services/
        fi
        if [[ ${ARCH} == 'armv7l' ]]; then
            echo "container is RPi"
            cp /srv/chains/misc/Docker/chains-config/default-services-slave/* /etc/chains/services/
            cp /srv/chains/misc/Docker/chains-config/default-services-rpi-slave/* /etc/chains/services/
        fi
    fi
    touch /chains-configured
else
    echo "Config exists, rolling on"
fi

## Remove this as soon as zeroconf-discoverd works again
if [ -n "$AMQP" ]; then
    IFS=: read host port <<< $AMQP
echo "main:
  host: $host
  port: $port
">/etc/chains/amqp.yml
fi


### daemon startups and ordering

# z-way zwave / razberry
if [ -f /opt/z-way-server/z-way-server ]; then
    supervisorctl start zway
    if [ -f /usr/sbin/mongoose ]; then
        supervisorctl start mongoose
    fi
fi

# only start telldusd if tellstick.conf exists:
if [ -f /opt/z-way-server/z-way-server ]; then
    supervisorctl start system:telldusd
fi

supervisorctl start system:nginx
#supervisorctl start chains:chains-zeroconf-discoverd # disabled until it runs properly
supervisorctl start chains:chains-manager

